services:
  damntv.frontend:
    image: ${DOCKER_REGISTRY-}damntv/frontend
    build:
      context: .
      dockerfile: Source/DamnTv.Frontend/DamnTv.Frontend/Dockerfile

  damntv.tgminiapp:
    image: ${DOCKER_REGISTRY-}damntv/miniapp
    build:
      context: .
      dockerfile: Source/DamnTv.TgMiniApp/Dockerfile
